package com.tanavota.tanavota.model.domain.articledetail

import android.annotation.SuppressLint
import android.os.Parcelable
import kotlinx.android.parcel.Parcelize

@SuppressLint("ParcelCreator")
@Parcelize
data class Article (
        val id: String,
        val site: String,
        val url: String,
        val name: String,
        val traffic: String,
        val location: String,
        val article_item: String,
        val price: String,
        val administrative_expense: String,
        val repair_financial_reserve: String,
        val tenancy: String,
        val premium: String,
        val deposit: String,
        val maintenance_cost: String,
        val lump_sum: String,
        val annual_planned_income: String,
        val yield: String,
        val layout: String,
        val storey: String,
        val building_area: String,
        val land_area: String,
        val building_structure: String,
        val time_old: String,
        val land_right: String,
        val city_planning: String,
        val restricted_zone: String,
        val coverage_ratio: String,
        val floor_area_ratio: String,
        val parking_lot: String,
        val motorcycle_place: String,
        val bicycle_parking_lot: String,
        val private_road_burden_area: String,
        val contact_with_road: String,
        val classification_of_land_and_category: String,
        val geographical_features: String,
        val the_total_number_of_houses: String,
        val country_law_report: String,
        val reform_and_renovation_important_notice: String,
        val special_report: String,
        val facilities: String,
        val remarks: String,
        val conditions: String,
        val present_condition: String,
        val delivery: String,
        val article_number: String,
        val information_pub_date: String,
        val next_time_update_due_date: String,
        val business_form: String,
        val created: String,
        val updated: String,
        val occupied_area: String,
        val balcony: String,
        val pet: String,
        val site_area: String,
        val management_form: String,
        val cost_per_square_meter: String,
        val deleted: String,
        val setback: String,
        val management_company: String,
        val management_employees: String,
        val main_opening: String,
        val other_area: String,
        val articleTypeName: String
) : Parcelable {
    companion object {
        fun empty(): Article = Article(
                id = "",
                site = "",
                url = "",
                name = "",
                traffic = "",
                location = "",
                article_item = "",
                price = "",
                administrative_expense = "",
                repair_financial_reserve = "",
                tenancy = "",
                premium = "",
                deposit = "",
                maintenance_cost = "",
                lump_sum = "",
                annual_planned_income = "",
                `yield` = "",
                layout = "",
                storey = "",
                building_area = "",
                land_area = "",
                building_structure = "",
                time_old = "",
                land_right = "",
                city_planning = "",
                restricted_zone = "",
                coverage_ratio = "",
                floor_area_ratio = "",
                parking_lot = "",
                motorcycle_place = "",
                bicycle_parking_lot = "",
                private_road_burden_area = "",
                contact_with_road = "",
                classification_of_land_and_category = "",
                geographical_features = "",
                the_total_number_of_houses = "",
                country_law_report = "",
                reform_and_renovation_important_notice = "",
                special_report = "",
                facilities = "",
                remarks = "",
                conditions = "",
                present_condition = "",
                delivery = "",
                article_number = "",
                information_pub_date = "",
                next_time_update_due_date = "",
                business_form = "",
                created = "",
                updated = "",
                occupied_area = "",
                balcony = "",
                pet = "",
                site_area = "",
                management_form = "",
                cost_per_square_meter = "",
                deleted = "",
                setback = "",
                management_company = "",
                management_employees = "",
                main_opening = "",
                other_area = "",
                articleTypeName = ""
        )
    }
}